[package]
name = "nostress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
clap = { version = "4.4.8", features = ["derive", "env"]}
nostr-sdk = "0.24.0"
rss = "2.0.6"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.33.0", features = ["full"]}
tracing = "0.1.40"

opentelemetry = { version = "0.20.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.13.0", features = ["grpc-tonic", "http-proto"] }
opentelemetry-semantic-conventions = "0.12.0"
opentelemetry_sdk = "0.20.0"

tracing-opentelemetry = "0.21.0"
tracing-subscriber = { version = "0.3.17", features = ["fmt", "json", "env-filter", "std", "registry"] }

tower-http = { version = "0.4.3", features = ["tracing", "trace"] }
