[package]
name = "nostress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.19"
clap = { version = "4.3.16", features = ["derive", "env"]}
nostr-sdk = "0.22.0"
rss = "2.0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"]}
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["fmt"]}
