[package]
name = "nostress"
version = "0.1.0"
edition = "2021"
description = "Nostr to RSS"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
clap = { version = "4.4.10", features = ["derive", "env"]}
nostr-sdk = "0.25.0"
rss = "2.0.6"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.34.0", features = ["full"]}
tracing = "0.1.40"

opentelemetry = { version = "0.21.0", features = [] }
opentelemetry-otlp = { version = "0.14.0", features = ["grpc-tonic", "http-proto"] }
opentelemetry-semantic-conventions = "0.13.0"
opentelemetry_sdk = { version = "0.21.1", features = ["rt-tokio"] }

tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "json", "env-filter", "std", "registry"] }

tower-http = { version = "0.5.0", features = ["tracing", "trace"] }
